# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_polling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingscript',
            name='comment',
        ),
        migrations.AlterField(
            model_name='pollingscript',
            name='tool_script',
            field=models.CharField(max_length=8000, verbose_name='脚本'),
        ),
    ]
