# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170521_2311'),
        ('deploy_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_project_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '前置业务',
                'verbose_name_plural': '前置业务',
            },
        ),
        migrations.CreateModel(
            name='ProjectHostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hostgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.HostGroup', verbose_name='主机组')),
            ],
            options={
                'verbose_name': '业务主机组',
                'verbose_name_plural': '业务主机组',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='host',
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='/home/kira/code/saltops/scripts/', verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='projecthostgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.Project', verbose_name='业务'),
        ),
        migrations.AddField(
            model_name='preproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.Project', verbose_name='前置业务'),
        ),
    ]
