# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '前置业务',
                'verbose_name': '前置业务',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='pre_project',
            field=models.ManyToManyField(blank=True, null=True, related_name='_project_pre_project_+', to='deploy_manager.Project', verbose_name='前置业务'),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='/Users/kira/oschina/saltops/scripts/files/', verbose_name='版本'),
        ),
        migrations.AddField(
            model_name='preproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deploy_manager.Project', verbose_name='前置业务'),
        ),
    ]
