# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectversion',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='./static/scripts/', validators=[django.core.validators.FileExtensionValidator(['zip'])], verbose_name='SLS包'),
        ),
    ]
