# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0002_auto_20170826_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='extra_param',
        ),
    ]
