# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_manager', '0003_remove_project_extra_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthost',
            name='deploy_states',
            field=models.IntegerField(choices=[(0, '未部署'), (1, '部署成功'), (2, '部署失败')], default=0, verbose_name='部署状态'),
        ),
    ]
