# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_hostgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.HostGroup', verbose_name='主机组'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='机房'),
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together=set([('idc', 'cabinet')]),
        ),
    ]
