# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170826_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idc',
            old_name='operator',
            new_name='isptype',
        ),
    ]
