# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20170826_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idc',
            old_name='type',
            new_name='idc_level_type',
        ),
        migrations.RenameField(
            model_name='idc',
            old_name='isptype',
            new_name='isp_type',
        ),
    ]
