# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20170410_1739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together=set([('idc', 'cabinet', 'name')]),
        ),
    ]
