# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 10:04
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20170826_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='cabinet',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='idc', chained_model_field='idc', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cabinet', verbose_name='机柜'),
        ),
    ]
