# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsscript',
            name='report_files',
            field=models.FileField(null=True, upload_to='./scripts/', verbose_name='报告模板'),
        ),
    ]
